from pydantic import BaseModel
from datetime import date, datetime
from typing import Optional

class EmployeeBase(BaseModel):
    license_rno: Optional[int]
    company_rno: Optional[int]
    employee_rno: Optional[int]
    employeeno: Optional[str]
    employee_firstname: Optional[str]
    employee_lastname: Optional[str]
    nric: Optional[str]
    birthdate: Optional[date]
    gender: Optional[str]
    contactno1: Optional[str]
    email: Optional[str]
    contactno2: Optional[str]
    address1: Optional[str]
    address2: Optional[str]
    address3: Optional[str]
    town: Optional[str]
    state: Optional[str]
    country: Optional[str]
    postcode: Optional[str]
    maritalstatus: Optional[str]
    nationality: Optional[str]
    race: Optional[str]
    joindate: Optional[date]
    resigndate: Optional[date]
    photo: Optional[str]
    isactive: Optional[bool]
    createdby: Optional[str]
    createdon: Optional[datetime]
    modifiedby: Optional[str]
    modifiedon: Optional[datetime]
    aliasname: Optional[str]