from pydantic import BaseModel
from datetime import time

class ShiftMaster(BaseModel):
    license_rno : int
    company_rno : int 
    shfmst_rno : int
    shfcode : int
    description : str
    restdaywrkrate : int
    offdaywrkrate : int
    holidaywrkrate : int
    wrkcalc_earlytime_p : bool
    wrkcalc_lateintime_m : bool
    wrkcalc_lateouttime_p : bool
    wrkcalc_earlyouttime_m : bool
    mealhrs_m : bool
    teahrs_m : bool
    isflexsibleshift : bool
    offsetlatein : bool
    mealcaltype : str
    minlateout : time
    graceminus : bool
    absorbgracetime : bool
    incompletemeal : bool
    offsetfrom : time 
    offsetto : time 
    mealfixhrs : time
    teafixhrs : time
    wrkrounding : int
    late_everymin : int
    late_deductmin : int
    earlyout_everymin : int
    earlyout_deductmin : int
    isfixsection : bool
    flex_dailyworkinghrstime : time
    otrate_norma : int
    otrate_off : int
    otrate_rest : int
    otrate_half : int
    otrate_holiday : int
    extotrate_normal : int
    extotrate_off : int
    extotrate_rest : int
    extotrate_half : int
    extotrate_holiday : int
    minothrsperday : time
    extminothrsperday : time
    extmaxothrsperday : time
    graceperiod_earlyout : time
    extendot : time
    otrounding : int 
    lateoutperiod : time
    otmaxtime : time
    isdeductlatein : bool
    isdeductearlyout : bool
    iswrkomitot : bool