from routes_file.routes_schemas.Company import Company
from routes_file.routes_schemas.Department import department

from routes_file.routes_schemas.Employee_class.ContactInformation import ContactInformation
from routes_file.routes_schemas.Employee_class.Employee import EmployeeBase
from routes_file.routes_schemas.Employee_class.Employment_Information import Employment_Information

from routes_file.routes_schemas.JobTitle import jobtitle
from routes_file.routes_schemas.Liscence import License

from routes_file.routes_schemas.User_password import users_password
from routes_file.routes_schemas.Users import users
from routes_file.routes_schemas.EmailInformation import EmailInformation



